VALORANT Champions Tour 2023 Data from https://www.kaggle.com/datasets/ryanluong1/valorant-champion-tour-2021-2023-data
Original data source: https://www.vlr.gg/vct-2023

In [1]:
import pandas as pd n

In [2]:
agents_pick_rates = pd.read_csv("../data/vct_2023/agents/agents_pick_rates.csv")
agents_pick_rates.head()

,Tournament,Stage,Match Type,Map,Agent,Pick Rate
0,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,omen,67%
1,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,skye,58%
2,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,raze,58%
3,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,breach,58%
4,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,killjoy,58%

In [3]:
maps_stats = pd.read_csv("../data/vct_2023/agents/maps_stats.csv")
maps_stats.head()

,Tournament,Stage,Match Type,Map,Total Maps Played,Attacker Side Win Percentage,Defender Side Win Percentage
0,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,All Maps,6,47%,53%
1,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Haven,2,40%,60%
2,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Bind,1,58%,42%
3,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,1,71%,29%
4,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Lotus,1,50%,50%

In [4]:
teams_picked_agents = pd.read_csv("../data/vct_2023/agents/teams_picked_agents.csv")
teams_picked_agents.head()

,Tournament,Stage,Match Type,Map,Team,Agent Picked,Total Wins By Map,Total Loss By Map,Total Maps Played
0,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,Team Heretics,omen,0,1,1
1,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,Team Heretics,skye,0,1,1
2,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,Team Heretics,raze,0,1,1
3,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,Team Heretics,viper,0,1,1
4,Champions Tour 2023: EMEA Last Chance Qualifier,Playoffs,Knockout Round,Fracture,Team Heretics,cypher,0,1,1

In [5]:
players_ids = pd.read_csv("../data/vct_2023/ids/players_ids.csv")
players_ids.head()

    Player  Player ID
0     nAts        457
1     Sayf        312
2  soulcas        101
3   Jamppi       9780
4   Redgar       1427

In [6]:
teams_ids = pd.read_csv("../data/vct_2023/ids/teams_ids.csv")
teams_ids.head()

            Team  Team ID
0    Team Liquid      474
1  Natus Vincere     4915
2            DRX     8185
3           LOUD     6961
4    FUT Esports     1184

In [7]:
tournaments_stages_match_types_ids = pd.read_csv("../data/vct_2023/ids/tournaments_stages_match_types_ids.csv")
tournaments_stages_match_types_ids.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Type ID
0,Champions Tour 2023: EMEA Last Chance Qualifier,1659,Playoffs,3147.0,Knockout Round,19811.0
1,Champions Tour 2023: EMEA Last Chance Qualifier,1659,Playoffs,3147.0,Upper Semifinals,19812.0
2,Champions Tour 2023: EMEA Last Chance Qualifier,1659,Playoffs,3147.0,Upper Final,19813.0
3,Champions Tour 2023: EMEA Last Chance Qualifier,1659,Playoffs,3147.0,Grand Final,19814.0
4,Champions Tour 2023: EMEA Last Chance Qualifier,1659,Playoffs,3147.0,Lower Round 1,19816.0

In [8]:
tournaments_stages_matches_games_ids = pd.read_csv("../data/vct_2023/ids/tournaments_stages_matches_games_ids.csv")
tournaments_stages_matches_games_ids.head()

,Tournament,Tournament ID,Stage,Stage ID,Match Type,Match Name,Match ID,Map,Game ID
0,Valorant Champions 2023,1657,Group Stage,3145,Opening (D),Team Liquid vs Natus Vincere,247100,Fracture,137395
1,Valorant Champions 2023,1657,Group Stage,3145,Opening (D),Team Liquid vs Natus Vincere,247100,Bind,137396
2,Valorant Champions 2023,1657,Group Stage,3145,Opening (D),DRX vs LOUD,247101,Lotus,137398
3,Valorant Champions 2023,1657,Group Stage,3145,Opening (D),DRX vs LOUD,247101,Split,137399
4,Valorant Champions 2023,1657,Group Stage,3145,Opening (D),DRX vs LOUD,247101,Ascent,137400

In [9]:
draft_phase = pd.read_csv("../data/vct_2023/matches/draft_phase.csv")
draft_phase.head()

,Tournament,Stage,Match Type,Match Name,Team,Action,Map
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Natus Vincere,ban,Haven
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Team Liquid,ban,Pearl
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Natus Vincere,pick,Fracture
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Team Liquid,pick,Bind
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Natus Vincere,ban,Lotus

In [10]:
eco_rounds = pd.read_csv("../data/vct_2023/matches/eco_rounds.csv")
eco_rounds.head()

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Loadout Value,Remaining Credits,Type,Outcome
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,1,Team Liquid,3.6k,0.4k,Eco: 0-5k,Win
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,1,Natus Vincere,3.5k,0.3k,Eco: 0-5k,Loss
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,2,Team Liquid,15.6k,4.1k,Semi-buy: 10-20k,Win
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,2,Natus Vincere,4.2k,6.4k,Eco: 0-5k,Loss
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,3,Team Liquid,13.3k,14.8k,Semi-buy: 10-20k,Win

In [11]:
eco_stats = pd.read_csv("../data/vct_2023/matches/eco_stats.csv")
eco_stats.head()

,Tournament,Stage,Match Type,Match Name,Map,Team,Type,Initiated,Won
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,Pistol Won,NaN,2
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,Eco (won),2.0,2
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,$ (won),2.0,0
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,$$ (won),8.0,4
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,$$$ (won),12.0,5

In [12]:
kills_stats = pd.read_csv("../data/vct_2023/matches/kills_stats.csv")
kills_stats.head()

,Tournament,Stage,Match Type,Match Name,Map,Team,Player,Agent,2k,3k,4k,5k,1v1,1v2,1v3,1v4,1v5,Econ,Spike Plants,Spike Defuse
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,soulcas,astra,4.0,1.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,30,2,0
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Sayf,breach,8.0,3.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,48,4,1
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,nAts,viper,13.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,58,2,1
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Redgar,sova,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38,5,0
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,neon,9.0,2.0,NaN,1.0,2.0,NaN,NaN,NaN,NaN,43,4,1

In [13]:
kills = pd.read_csv("../data/vct_2023/matches/kills.csv")
kills.head()

,Tournament,Stage,Match Type,Match Name,Map,Player Team,Player,Enemy Team,Enemy,Player Kills,Enemy Kills,Difference,Kill Type
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,Natus Vincere,ANGE1,9.0,12.0,-3.0,All Kills
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,Natus Vincere,SUYGETSU,6.0,10.0,-4.0,All Kills
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,Natus Vincere,Zyppan,8.0,7.0,1.0,All Kills
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,Natus Vincere,cNed,7.0,5.0,2.0,All Kills
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,All Maps,Team Liquid,Jamppi,Natus Vincere,Shao,8.0,4.0,4.0,All Kills

In [14]:
maps_played = pd.read_csv("../data/vct_2023/matches/maps_played.csv")
maps_played.head()

,Tournament,Stage,Match Type,Match Name,Map
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Bind
2,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Lotus
3,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Split
4,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Ascent

In [15]:
maps_scores = pd.read_csv("../data/vct_2023/matches/maps_scores.csv")
maps_scores.head()

,Tournament,Stage,Match Type,Match Name,Map,Team A,Team A Score,Team A Attacker Score,Team A Defender Score,Team A Overtime Score,Team B,Team B Score,Team B Attacker Score,Team B Defender Score,Team B Overtime Score,Duration
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,11,6,5,NaN,Natus Vincere,13,7,6,NaN,1:18:55
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Bind,Team Liquid,15,7,5,3.0,Natus Vincere,17,7,5,5.0,1:22:57
2,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Lotus,DRX,13,7,5,1.0,LOUD,15,7,5,3.0,1:17:19
3,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Split,DRX,13,8,5,NaN,LOUD,6,2,4,NaN,47:47
4,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Ascent,DRX,13,8,5,NaN,LOUD,8,4,4,NaN,NaN

In [16]:
overview = pd.read_csv("../data/vct_2023/matches/overview.csv")
overview.head()

,Tournament,Stage,Match Type,Match Name,Map,Player,Team,Agents,Rating,Average Combat Score,...,Deaths,Assists,Kills - Deaths (KD),"Kill, Assist, Trade, Survive %",Average Damage per Round,Headshot %,First Kills,First Deaths,Kills - Deaths (FKD),Side
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,nAts,Team Liquid,viper,1.20,242.0,...,15.0,3.0,5.0,67%,144.0,33%,3.0,3.0,0.0,both
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,nAts,Team Liquid,viper,1.40,268.0,...,7.0,1.0,5.0,75%,162.0,46%,1.0,1.0,0.0,attack
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,nAts,Team Liquid,viper,1.00,217.0,...,8.0,2.0,0.0,58%,125.0,21%,2.0,2.0,0.0,defend
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Sayf,Team Liquid,breach,0.96,170.0,...,16.0,10.0,-2.0,71%,112.0,23%,0.0,1.0,-1.0,both
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Sayf,Team Liquid,breach,0.46,81.0,...,10.0,6.0,-8.0,58%,50.0,20%,0.0,0.0,0.0,attack

In [17]:
rounds_kills = pd.read_csv("../data/vct_2023/matches/rounds_kills.csv")
rounds_kills.head()

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Eliminator Team,Eliminator,Eliminator Agent,Eliminated Team,Eliminated,Eliminated Agent,Kill Type
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Round 1,Team Liquid,soulcas,astra,Natus Vincere,cNed,killjoy,2k
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Round 1,Team Liquid,soulcas,astra,Natus Vincere,Shao,fade,2k
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Round 17,Team Liquid,soulcas,astra,Natus Vincere,ANGE1,omen,2k
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Round 17,Team Liquid,soulcas,astra,Natus Vincere,Zyppan,raze,2k
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Round 17,Team Liquid,soulcas,astra,Team Liquid,soulcas,astra,2k

In [18]:
scores = pd.read_csv("../data/vct_2023/matches/scores.csv")
scores.head()

,Tournament,Stage,Match Type,Match Name,Team A,Team B,Team A Score,Team B Score,Match Result
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Team Liquid,Natus Vincere,0,2,Natus Vincere won
1,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,DRX,LOUD,2,1,DRX won
2,Valorant Champions 2023,Group Stage,Opening (B),FUT Esports vs T1,FUT Esports,T1,2,0,FUT Esports won
3,Valorant Champions 2023,Group Stage,Opening (B),Evil Geniuses vs FunPlus Phoenix,Evil Geniuses,FunPlus Phoenix,2,0,Evil Geniuses won
4,Valorant Champions 2023,Group Stage,Winner's (D),Natus Vincere vs DRX,Natus Vincere,DRX,1,2,DRX won

In [19]:
team_mapping = pd.read_csv("../data/vct_2023/matches/team_mapping.csv")
team_mapping.head()

  Abbreviated      Full Name
0          TL    Team Liquid
1        NAVI  Natus Vincere
2         DRX            DRX
3        LOUD           LOUD
4         FUT    FUT Esports

In [20]:
win_loss_methods_count = pd.read_csv("../data/vct_2023/matches/win_loss_methods_count.csv")
win_loss_methods_count.head()

,Tournament,Stage,Match Type,Match Name,Map,Team,Elimination,Detonated,Defused,Time Expiry (No Plant),Eliminated,Defused Failed,Detonation Denied,Time Expiry (Failed to Plant)
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Team Liquid,8,2,1,0,6,5,1,1
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,Natus Vincere,6,5,1,1,8,2,1,0
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Bind,Team Liquid,11,1,2,1,11,1,4,1
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Bind,Natus Vincere,11,1,4,1,11,1,2,1
4,Valorant Champions 2023,Group Stage,Opening (D),DRX vs LOUD,Lotus,DRX,5,4,3,1,8,2,4,1

In [21]:
win_loss_methods_round_number = pd.read_csv("../data/vct_2023/matches/win_loss_methods_round_number.csv")
win_loss_methods_round_number.head()

,Tournament,Stage,Match Type,Match Name,Map,Round Number,Team,Method,Outcome
0,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,1,Team Liquid,Elimination,Win
1,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,1,Natus Vincere,Eliminated,Loss
2,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,2,Team Liquid,Elimination,Win
3,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,2,Natus Vincere,Eliminated,Loss
4,Valorant Champions 2023,Group Stage,Opening (D),Team Liquid vs Natus Vincere,Fracture,3,Team Liquid,Elimination,Win

In [22]:
players_stats = pd.read_csv("../data/vct_2023/players_stats/players_stats.csv")
players_stats.head()

,Tournament,Stage,Match Type,Player,Team,Agents,Rounds Played,Rating,Average Combat Score,Kills:Deaths,...,First Deaths Per Round,Headshot %,Clutch Success %,Clutches (won/played),Maximum Kills in a Single Map,Kills,Deaths,Assists,First Kills,First Deaths
0,Champions Tour 2023: Americas Last Chance Qual...,Main Event,Upper Round 1,Melser,KRÜ Esports,brimstone,20,1.14,256.0,1.21,...,0.15,32%,NaN,0/1,17,17,14,9,2,3
1,Champions Tour 2023: Americas Last Chance Qual...,Main Event,Upper Round 1,Melser,KRÜ Esports,omen,21,1.12,216.0,1.38,...,0.05,25%,33%,1/3,18,18,13,1,4,1
2,Champions Tour 2023: Americas Last Chance Qual...,Main Event,Upper Round 1,Melser,KRÜ Esports,"brimstone, omen",41,1.13,236.0,1.30,...,0.10,28%,25%,1/4,18,35,27,10,6,4
3,Champions Tour 2023: Americas Last Chance Qual...,Main Event,Upper Round 1,DaveeyS,KRÜ Esports,killjoy,21,1.29,253.0,1.46,...,0.00,27%,100%,1/1,19,19,13,7,2,0
4,Champions Tour 2023: Americas Last Chance Qual...,Main Event,Upper Round 1,keznit,KRÜ Esports,raze,41,1.24,262.5,1.30,...,0.10,15%,NaN,0/3,20,35,27,16,6,4